name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
commitish: dev
filter-by-commitish: true
# exclude-labels:
#   - 'skip-changelog'
# autolabeler:
#   - label: 'skip-changelog'
#     branch:
#       - '/^dev$/'
template: |
  ## What’s Changed
  $CHANGES
